name: verthash-one-click-miner
version: 2.1.5
summary:   Open Source Vertcoin One-Click Miner and Dogecoin wallet.
description: |
  This program will create a Dogecoin wallet that only you have access to. 
  Encrypt your wallet with a password that you will not forget. It will then 
  create the Verthash datafile and immediately begin mining Vertcoin. You will 
  receive payouts in Dogecoin to your built-in Dogecoin wallet from the pool 
  selected in Settings. 
  Additional payout currencies via Zergpool and zpool are available in Settings.

grade: stable
confinement: strict

apps:
  ocm:
    command: desktop-launch verthash-ocm
    plugs: [home, network, network-bind, desktop, x11, unity7]
    environment:
      # Override HOME so the datadir is located at
      # ~/snap/verthash-one-click-miner/common/.verthash-ocm/ instead of
      # ~/snap/verthash-one-click-miner/current/.verthash-ocm/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1

parts:
  verthash-one-click-miner:
    plugin: nil
    override-build: | 
      env | grep SNAP
      wget https://github.com/vertiond/verthash-one-click-miner/releases/download/${SNAPCRAFT_PROJECT_VERSION}/manifest-${SNAPCRAFT_PROJECT_VERSION}.txt
      wget https://github.com/vertiond/verthash-one-click-miner/releases/download/${SNAPCRAFT_PROJECT_VERSION}/verthash-ocm-${SNAPCRAFT_PROJECT_VERSION}-linux-x64.zip
      echo "1c01782d8cc597ef26dbcd996ae8dd701aa4cf5b995a7465f2f691294a057d6d  manifest-${SNAPCRAFT_PROJECT_VERSION}.txt" | sha256sum --check
      sha256sum --ignore-missing --check manifest-${SNAPCRAFT_PROJECT_VERSION}.txt
      unzip verthash-ocm-${SNAPCRAFT_PROJECT_VERSION}-linux-x64.zip
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin verthash-one-click-miner-${SNAPCRAFT_PROJECT_VERSION}/bin/verthash-ocm
      wget https://raw.githubusercontent.com/vertcoin-project/vertcoin-core/master/share/pixmaps/vertcoin128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps vertcoin128.png
    build-packages:
      - wget zip
    after:
      - desktop-gtk3
